### ISSUE TITLE
Updates to the library

### ISSUE THREAD

**Issue by mikecx** [briansokol/react-paginatify#1]
Hey,

First off, thanks for the first react pagination library that worked as expected of the box for me :). Probably tried and was frustrated by five others before I found yours.

Any chance you could remove the comment on line 132, update the dependencies, and publish a new version? Would definitely appreciate it!

**Comment by briansokol** [comment]
Yes definitely. I'm glad you like it! I should be able to take a look at this before the end of this weekend. I'll need to see if it's going to break anything if I update to the latest versions of Babel and Webpack, for example, and make sure it's still compatible with the latest React. Everything else shouldn't be an issue.

**Comment by mikecx** [comment]
:+1: Thanks!
